get:
  tags:
    - Task
  summary: 'Create a task form.'
  operationId: create_task
  responses:
    200:
      description: 'The create task information.'
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: ../../models/task.yml
              meta:
                type: object
    401:
      description: Unauthorized
    403:
      description: Forbidden
